# Generated by Django 5.1.4 on 2024-12-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_preference_customuser_alter_notes_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
