# Generated by Django 5.1.4 on 2024-12-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], default='science', max_length=20, null=True),
        ),
    ]
